-- ============================================================
-- V3: Add tenant groups and nullable tenant ownership (PostgreSQL)
-- ============================================================

CREATE TABLE IF NOT EXISTS scheduling_tenant_groups (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code  VARCHAR(64)  NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    active       BOOLEAN      DEFAULT TRUE,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tenant_groups_code UNIQUE (tenant_code)
);

ALTER TABLE scheduling_clinics
    ADD COLUMN IF NOT EXISTS tenant_group_id BIGINT NULL;

ALTER TABLE scheduling_holidays
    ADD COLUMN IF NOT EXISTS tenant_group_id BIGINT NULL;

ALTER TABLE scheduling_holidays
    DROP CONSTRAINT IF EXISTS scheduling_holidays_holiday_date_key;
